import axios from 'axios';
const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const api = axios.create({ baseURL: BASE_URL });
api.interceptors.request.use(cfg => {
  const token = localStorage.getItem('erp_token');
  if (token) cfg.headers.Authorization = `Bearer ${token}`;
  return cfg;
});
api.interceptors.response.use(res => res, err => {
  if (err.response?.status === 401) { localStorage.removeItem('erp_token'); localStorage.removeItem('erp_user'); window.location.href = '/login'; }
  return Promise.reject(err);
});
export const authAPI = { login: d=>api.post('/auth/login',d), me:()=>api.get('/auth/me'), getUsers:()=>api.get('/auth/users'), createUser:d=>api.post('/auth/users',d), updateUser:(id,d)=>api.put(`/auth/users/${id}`,d), deleteUser:id=>api.delete(`/auth/users/${id}`), getRoles:()=>api.get('/auth/roles'), changePassword:d=>api.put('/auth/me/password',d) };
export const inventoryAPI = { getCategories:()=>api.get('/inventory/categories'), createCategory:d=>api.post('/inventory/categories',d), getItems:()=>api.get('/inventory/items'), createItem:d=>api.post('/inventory/items',d), updateItem:(id,d)=>api.put(`/inventory/items/${id}`,d), getWarehouses:()=>api.get('/inventory/warehouses'), createWarehouse:d=>api.post('/inventory/warehouses',d), createMovement:d=>api.post('/inventory/movements',d), getMovements:p=>api.get('/inventory/movements',{params:p}), getBalance:p=>api.get('/inventory/balance',{params:p}), getLedger:p=>api.get('/inventory/ledger',{params:p}), getHsnCodes:()=>api.get('/inventory/hsn-codes'), createHsnCode:d=>api.post('/inventory/hsn-codes',d) };
export const stonesAPI = { getBlocks:()=>api.get('/stones/blocks'), createBlock:d=>api.post('/stones/blocks',d), getBlock:id=>api.get(`/stones/blocks/${id}`), splitBlock:(id,d)=>api.post(`/stones/blocks/${id}/split`,d), getChildren:id=>api.get(`/stones/blocks/${id}/children`), getGenealogy:id=>api.get(`/stones/blocks/${id}/genealogy`) };
export const blueprintsAPI = { getStructures:()=>api.get('/blueprints/structures'), createStructure:d=>api.post('/blueprints/structures',d), getLayers:id=>api.get(`/blueprints/structures/${id}/layers`), createLayer:d=>api.post('/blueprints/layers',d), getPositions:p=>api.get('/blueprints/positions',{params:p}), createPosition:d=>api.post('/blueprints/positions',d), getDependencies:p=>api.get('/blueprints/dependencies',{params:p}), createDependency:d=>api.post('/blueprints/dependencies',d), deleteDependency:id=>api.delete(`/blueprints/dependencies/${id}`), getGapReport:id=>api.get(`/blueprints/structures/${id}/gap-report`), updatePositionStatus:(id,d)=>api.put(`/blueprints/positions/${id}/status`,d) };
export const projectsAPI = { getProjects:()=>api.get('/projects'), createProject:d=>api.post('/projects',d), getProject:id=>api.get(`/projects/${id}`), updateProject:(id,d)=>api.put(`/projects/${id}`,d), deleteProject:id=>api.delete(`/projects/${id}`) };
export const mfgAPI = { getIdols:()=>api.get('/manufacturing/idols'), createIdol:d=>api.post('/manufacturing/idols',d), getIdol:id=>api.get(`/manufacturing/idols/${id}`), createStage:d=>api.post('/manufacturing/stages',d), updateStage:(id,d)=>api.put(`/manufacturing/stages/${id}`,d), getIdolStages:id=>api.get(`/manufacturing/idols/${id}/stages`), createComponent:d=>api.post('/manufacturing/components',d), updateComponentStatus:(id,d)=>api.put(`/manufacturing/components/${id}/status`,d) };
export const allocationsAPI = { allocate:d=>api.post('/allocations',d), release:id=>api.delete(`/allocations/${id}`), getAllocations:()=>api.get('/allocations'), transfer:d=>api.post('/allocations/transfers',d) };
export const jobWorkAPI = { getChallans:()=>api.get('/job-work'), createChallan:d=>api.post('/job-work',d), getChallan:id=>api.get(`/job-work/${id}`), returnChallan:(id,d)=>api.put(`/job-work/${id}/return`,d) };
export const siteAPI = { getDispatches:()=>api.get('/site/dispatches'), createDispatch:d=>api.post('/site/dispatches',d), getEwayBill:id=>api.get(`/site/dispatches/${id}/eway-bill`), getInstallations:()=>api.get('/site/installations'), createInstallation:d=>api.post('/site/installations',d), verifyInstallation:(id,d)=>api.put(`/site/installations/${id}/verify`,d) };
export const contractorsAPI = { getContractors:()=>api.get('/contractors'), createContractor:d=>api.post('/contractors',d), getContractor:id=>api.get(`/contractors/${id}`), updateContractor:(id,d)=>api.put(`/contractors/${id}`,d), deleteContractor:id=>api.delete(`/contractors/${id}`), getAgreements:()=>api.get('/contractors/agreements'), createAgreement:d=>api.post('/contractors/agreements',d), getInvoices:()=>api.get('/contractors/invoices'), createInvoice:d=>api.post('/contractors/invoices',d), payInvoice:(id,d)=>api.put(`/contractors/invoices/${id}/payment`,d) };
export const billingAPI = { getMilestones:()=>api.get('/billing/milestones'), createMilestone:d=>api.post('/billing/milestones',d), updateMilestone:(id,d)=>api.put(`/billing/milestones/${id}`,d), getInvoices:()=>api.get('/billing/invoices'), createInvoice:d=>api.post('/billing/invoices',d), getInvoice:id=>api.get(`/billing/invoices/${id}`), payInvoice:(id,d)=>api.put(`/billing/invoices/${id}/payment`,d), getAdvancePayments:()=>api.get('/billing/advance-payments'), createAdvancePayment:d=>api.post('/billing/advance-payments',d) };
export const gstAPI = { calculate:p=>api.get('/gst/calculate',{params:p}), getGstr1:p=>api.get('/gst/gstr1',{params:p}), getProjectCosts:()=>api.get('/gst/project-costs'), createProjectCost:d=>api.post('/gst/project-costs',d), getProjectMargin:id=>api.get(`/gst/project-margin/${id}`) };
export const auditAPI = { getLogs:p=>api.get('/audit/logs',{params:p}) };
export default api;
