import { useState, useEffect } from 'react';
import { inventoryAPI } from '../services/api.jsx';
import { PageTitle, Card, Table, Btn, Modal, FormField, Input, Select, Badge, AlertBox, StatCard } from '../components/UI.jsx';
export default function InventoryPage() {
  const [tab,setTab]=useState('items');
  const [items,setItems]=useState([]);
  const [categories,setCategories]=useState([]);
  const [warehouses,setWarehouses]=useState([]);
  const [movements,setMovements]=useState([]);
  const [loading,setLoading]=useState(true);
  const [modal,setModal]=useState(null);
  const [form,setForm]=useState({});
  const [err,setErr]=useState('');
  const [saving,setSaving]=useState(false);
  const load=()=>{setLoading(true);Promise.allSettled([inventoryAPI.getItems(),inventoryAPI.getCategories(),inventoryAPI.getWarehouses(),inventoryAPI.getMovements()]).then(([i,c,w,m])=>{setItems(i.value?.data||[]);setCategories(c.value?.data||[]);setWarehouses(w.value?.data||[]);setMovements(m.value?.data||[]);setLoading(false);});};
  useEffect(load,[]);
  const f=k=>e=>setForm(x=>({...x,[k]:e.target.value}));
  const saveItem=async()=>{if(!form.name||!form.category_id)return setErr('Name and category required');setSaving(true);try{await inventoryAPI.createItem(form);setModal(null);load();}catch(e){setErr(e.response?.data?.detail||'Failed');}setSaving(false);};
  const saveCategory=async()=>{if(!form.name)return setErr('Name required');setSaving(true);try{await inventoryAPI.createCategory(form);setModal(null);load();}catch(e){setErr(e.response?.data?.detail||'Failed');}setSaving(false);};
  const saveWarehouse=async()=>{if(!form.name)return setErr('Name required');setSaving(true);try{await inventoryAPI.createWarehouse(form);setModal(null);load();}catch(e){setErr(e.response?.data?.detail||'Failed');}setSaving(false);};
  const saveMovement=async()=>{if(!form.item_id||!form.warehouse_id||!form.movement_type||!form.quantity)return setErr('All fields required');setSaving(true);try{await inventoryAPI.createMovement({...form,quantity:Number(form.quantity)});setModal(null);load();}catch(e){setErr(e.response?.data?.detail||'Failed');}setSaving(false);};
  const TABS=[{id:'items',label:'Items'},{id:'categories',label:'Categories'},{id:'warehouses',label:'Warehouses'},{id:'movements',label:'Movements'}];
  return (
    <div>
      <PageTitle icon="📦" title="Inventory Management" subtitle="Items, stock levels, movements and warehouses" action={<div style={{display:'flex',gap:8}}><Btn variant="ghost" size="sm" onClick={()=>{setForm({});setErr('');setModal('category');}}>+ Category</Btn><Btn variant="ghost" size="sm" onClick={()=>{setForm({});setErr('');setModal('warehouse');}}>+ Warehouse</Btn><Btn size="sm" onClick={()=>{setForm({});setErr('');setModal('movement');}}>+ Movement</Btn><Btn onClick={()=>{setForm({});setErr('');setModal('item');}}>+ Item</Btn></div>}/>
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:24}}>
        <StatCard icon="📦" label="Items" value={items.length} color="#f97316"/><StatCard icon="🗂️" label="Categories" value={categories.length} color="#1e40af"/><StatCard icon="🏭" label="Warehouses" value={warehouses.length} color="#16a34a"/><StatCard icon="🔄" label="Movements" value={movements.length} color="#7c3aed"/>
      </div>
      <div style={{display:'flex',gap:4,marginBottom:16}}>{TABS.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'7px 18px',border:'none',borderRadius:8,cursor:'pointer',fontSize:13,fontWeight:tab===t.id?600:400,background:tab===t.id?'#0f2d5a':'#f0f4fa',color:tab===t.id?'#fff':'#374151',fontFamily:"'Plus Jakarta Sans',sans-serif"}}>{t.label}</button>)}</div>
      <Card>
        {tab==='items'&&<Table loading={loading} data={items} columns={[{key:'item_code',label:'Code'},{key:'name',label:'Name',render:v=><span style={{fontWeight:600}}>{v}</span>},{key:'category_id',label:'Category',render:v=>categories.find(c=>c.id===v)?.name||v},{key:'item_type',label:'Type',render:v=><Badge label={v} color={v==='serialized'?'purple':v==='batch'?'blue':'orange'}/>},{key:'unit_of_measure',label:'UoM'},{key:'hsn_code',label:'HSN'},{key:'gst_rate',label:'GST%',render:v=>v?`${v}%`:'—'}]}/>}
        {tab==='categories'&&<Table loading={loading} data={categories} columns={[{key:'name',label:'Name',render:v=><span style={{fontWeight:600}}>{v}</span>},{key:'description',label:'Description'}]}/>}
        {tab==='warehouses'&&<Table loading={loading} data={warehouses} columns={[{key:'name',label:'Name',render:v=><span style={{fontWeight:600}}>{v}</span>},{key:'warehouse_type',label:'Type',render:v=><Badge label={v} color="blue"/>},{key:'location',label:'Location'},{key:'is_active',label:'Status',render:v=><Badge label={v?'Active':'Inactive'} color={v?'green':'red'}/>}]}/>}
        {tab==='movements'&&<Table loading={loading} data={movements} columns={[{key:'movement_type',label:'Type',render:v=><Badge label={v} color={v==='inward'?'green':v==='outward'?'red':'blue'}/>},{key:'item_id',label:'Item',render:v=>items.find(i=>i.id===v)?.name||v},{key:'warehouse_id',label:'Warehouse',render:v=>warehouses.find(w=>w.id===v)?.name||v},{key:'quantity',label:'Qty'},{key:'created_at',label:'Date',render:v=>v?new Date(v).toLocaleDateString('en-IN'):'—'}]}/>}
      </Card>
      <Modal open={modal==='item'} onClose={()=>setModal(null)} title="Add Item"><AlertBox type="error" msg={err}/><FormField label="Name" required><Input value={form.name||''} onChange={f('name')} placeholder="Item name"/></FormField><FormField label="Category" required><Select value={form.category_id||''} onChange={f('category_id')}><option value="">Select…</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></FormField><FormField label="Type"><Select value={form.item_type||'batch'} onChange={f('item_type')}><option value="batch">Batch</option><option value="serialized">Serialized</option><option value="dimensional">Dimensional</option></Select></FormField><FormField label="UoM"><Input value={form.unit_of_measure||''} onChange={f('unit_of_measure')} placeholder="pcs/kg/sqft"/></FormField><FormField label="HSN Code"><Input value={form.hsn_code||''} onChange={f('hsn_code')}/></FormField><FormField label="GST %"><Input type="number" value={form.gst_rate||''} onChange={f('gst_rate')} placeholder="18"/></FormField><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><Btn variant="ghost" onClick={()=>setModal(null)}>Cancel</Btn><Btn onClick={saveItem} disabled={saving}>{saving?'Saving…':'Save'}</Btn></div></Modal>
      <Modal open={modal==='category'} onClose={()=>setModal(null)} title="Add Category"><AlertBox type="error" msg={err}/><FormField label="Name" required><Input value={form.name||''} onChange={f('name')}/></FormField><FormField label="Description"><Input value={form.description||''} onChange={f('description')}/></FormField><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><Btn variant="ghost" onClick={()=>setModal(null)}>Cancel</Btn><Btn onClick={saveCategory} disabled={saving}>{saving?'Saving…':'Save'}</Btn></div></Modal>
      <Modal open={modal==='warehouse'} onClose={()=>setModal(null)} title="Add Warehouse"><AlertBox type="error" msg={err}/><FormField label="Name" required><Input value={form.name||''} onChange={f('name')}/></FormField><FormField label="Type"><Select value={form.warehouse_type||'main'} onChange={f('warehouse_type')}><option value="main">Main</option><option value="site">Site</option><option value="job_work">Job Work</option><option value="transit">Transit</option></Select></FormField><FormField label="Location"><Input value={form.location||''} onChange={f('location')}/></FormField><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><Btn variant="ghost" onClick={()=>setModal(null)}>Cancel</Btn><Btn onClick={saveWarehouse} disabled={saving}>{saving?'Saving…':'Save'}</Btn></div></Modal>
      <Modal open={modal==='movement'} onClose={()=>setModal(null)} title="Record Movement"><AlertBox type="error" msg={err}/><FormField label="Type" required><Select value={form.movement_type||''} onChange={f('movement_type')}><option value="">Select…</option><option value="inward">Inward</option><option value="outward">Outward</option><option value="transfer">Transfer</option></Select></FormField><FormField label="Item" required><Select value={form.item_id||''} onChange={f('item_id')}><option value="">Select…</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></FormField><FormField label="Warehouse" required><Select value={form.warehouse_id||''} onChange={f('warehouse_id')}><option value="">Select…</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></FormField><FormField label="Quantity" required><Input type="number" value={form.quantity||''} onChange={f('quantity')}/></FormField><FormField label="Reference No"><Input value={form.reference_no||''} onChange={f('reference_no')} placeholder="PO/DC/GRN"/></FormField><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><Btn variant="ghost" onClick={()=>setModal(null)}>Cancel</Btn><Btn onClick={saveMovement} disabled={saving}>{saving?'Saving…':'Record'}</Btn></div></Modal>
    </div>
  );
}
